-dontoptimize
-dontobfuscate
-dontusemixedcaseclassnames
-dontnote android.support.v4.**
-dontwarn android.support.v4.**
-dontnote android.support.v7.**
-dontwarn android.support.v7.**
-dontnote com.android.billingclient.**
-dontwarn com.android.billingclient.**
-dontnote com.google.android.gms.**
-dontwarn com.google.android.gms.**
-dontwarn com.caddish_hedgehog.hedgecam2.**

-keep class com.android.vending.billing.** {*;}
